#!/usr/bin/env bash
# cria um .md de um sonho nulo ou com conteúdo no obsidian

source /mnt/seagate/bash/internal/config.sh

year=$(date +"%Y") # obtém só o ano atual
current_dream_journal=$OBSIDIAN_VAULTS/$VAULT_NAME_DREAMS/dream-log/$year
dream_journal_relative=/dream-log/$year

today=$(date +"%Y-%m-%d") # obtém a data atual e formata ela pra iso 8601
already_regisred=false # declara se o sonho de hoje já foi registrado ou não (é uma string, não um boolean de verdade) 

for md_file in $current_dream_journal/*.md; do
    # basename retorna só o nome do arquivo em vez do path completo
    file_name=$(basename "$md_file")

    # corta o nome do arquivo de 0 até 10, que é a quantidade que o formato de data em iso tem
    # assim, o nome do arquivo é desconsiderado e apenas a data permanece
    date_on_name=${file_name:0:10}
    
    # sinalizar caso um sonho com a mesma data já exista
    if [[ $date_on_name == $today ]]; then
        already_regisred=true
        break
    fi
done

if [[ $already_regisred != true ]]; then
    # obter o título do sonho caso ele seja passado com -t ou --title
    TITLE=""

    while [[ $# -gt 0 ]]; do
        case "$1" in
            -t|--title)
                TITLE="$2"
                shift 2
                ;;
            *)
                shift
                ;;
        esac
    done

    # se o título tiver caracteres não suportados, sai do script indicando erro (exit 1)
    if [[ "$TITLE" =~ [^a-zA-Z0-9_-] ]]; then
        echo "⚠️ o título contém espaços ou caracteres especiais"
        exit 1
    fi

    # definir o nome final do arquivo markdown
    # se o title não for nulo, atribui ele a nota, se não, nomeia ela como null
    if [[ -n "$TITLE" ]]; then
        entry_name=$today"_"$TITLE".md"
    else
        entry_name=$today"_null.md"
    fi

    # registar o sonho no path final
    > $current_dream_journal/$entry_name
    echo "🌒 sonho anotado com sucesso"
    echo $current_dream_journal/$entry_name

    # abrir o obsidian pra editar a nota caso ele tenha título
    if [[ -n "$TITLE" ]]; then
        echo "🪫 a nota possui um título. abrindo o obsidian..."
        xdg-open "obsidian://open?vault=$NAME_VAULT_DREAMS&file=$dream_journal_relative/$entry_name"
    fi
else
    echo "💉 o sonho de hoje já foi anotado"
fi